### ISSUE TITLE
White Wine Quality Predictor

### ISSUE THREAD

**Issue by AshishKingdom** [DSC-JSS-NOIDA/ML-Hub#11]
- **Objective** : To create a model which can predict the quality of wine.
- **Dataset Link** : https://www.kaggle.com/datasets/piyushagni5/white-wine-quality
- Do Exploratory Data Analysis, create models using different algorithms and compare them using evaluation metrics.

**Comment by maulanaakbardj** [comment]
Hi, I'd like to be assigned to this issue.

**Comment by Aakarsh00** [comment]
Hello, Can you assign me this issue?

**Comment by srivasPankhuri** [comment]
@maulanaakbardj go ahead !
