### ISSUE TITLE
Individual Medical Cost Prediction

### ISSUE THREAD

**Issue by divik2510** [DSC-JSS-NOIDA/ML-Hub#16]
• **Objective** : Create a model to predict Individual Medical Cost.
• **Dataset** : https://www.kaggle.com/datasets/mirichoi0218/insurance
• Do Exploratory Data Analysis, create models using different algorithms and compare them using accuracy scores

**Comment by sanvisharma003** [comment]
heyy.. what is the problem.. like we have to do what ?

**Comment by srivasPankhuri** [comment]
Hi @sanvisharma003 ! 
You have to perform EDA on the dataset provided and create different regression models to predict individual Medical Cost and at the end compare them all using some Evaluation metrics.

The link to the dataset has been updated, you can access it now.

**Comment by Aakarsh00** [comment]
Can you assign me this model

**Comment by Manomay15** [comment]
Hello, I would like to contribute here. Can I work on it?

**Comment by srivasPankhuri** [comment]
Sure @Manomay15, go ahead!

**Comment by ayushthe1** [comment]
hey @srivasPankhuri , Can i also work on this ?

**Comment by ayushthe1** [comment]
hey @srivasPankhuri , i made a pr for this problem .Can you please check it and give some feedback.

**Comment by srivasPankhuri** [comment]
Hi @ayushthe1 yes your PR has been merged after reviewing

**Comment by srivasPankhuri** [comment]
@Manomay15 you can still work on this issue if you wish to just change the name of the folder to Individual Medical Cost Prediction-2

**Comment by ayushthe1** [comment]
> Hi @ayushthe1 yes your PR has been merged after reviewing

Thanks !
