### ISSUE TITLE
Air Quality Prediction

### ISSUE THREAD

**Issue by srivasPankhuri** [DSC-JSS-NOIDA/ML-Hub#29]
• **Objective** : To build a model to predict Air Quality
• **Dataset** : https://www.kaggle.com/datasets/rohanrao/air-quality-data-in-india
• Do Exploratory Data Analysis, create models using different algorithms and compare them using evaluation metrics.

**Comment by disuja7** [comment]
Hey @srivasPankhuri, Can you assign this task to me.

**Comment by srivasPankhuri** [comment]
@disuja7 assigning it to you
