### ISSUE TITLE
Brain Stroke Prediction

### ISSUE THREAD

**Issue by srivasPankhuri** [DSC-JSS-NOIDA/ML-Hub#3]
•Objective : To create a prediction model for Brain Stroke Prediction
•Dataset : https://www.kaggle.com/code/aashidutt3/brain-stroke-prediction
•Do Exploratory Data Analysis, create models using different algorithms and compare them using evaluation metrics.

**Comment by AAnirudh07** [comment]
Can I be assigned to this issue pls?

**Comment by srivasPankhuri** [comment]
Alright @AAnirudh07 go ahead

**Comment by AAnirudh07** [comment]
#21
