### ISSUE TITLE
Book Genre Prediction

### ISSUE THREAD

**Issue by AshishKingdom** [DSC-JSS-NOIDA/ML-Hub#31]
- **Objective** : To create a model which can predict the genre of book
- **Dataset Link** : https://www.kaggle.com/datasets/athu1105/book-genre-prediction
- Do Exploratory Data Analysis, create models using different algorithms and compare them using evaluation metrics.

**Comment by deathsurgeon1** [comment]
Hi @AshishKingdom @srivasPankhuri I would like to work on this

**Comment by AshishKingdom** [comment]
@deathsurgeon1 okay! go ahead!
