### ISSUE TITLE
Food Delivery Time

### ISSUE THREAD

**Issue by AshishKingdom** [DSC-JSS-NOIDA/ML-Hub#32]
- **Objective** : To create a model which can predict the delivery time of food.
- **Dataset Link** : https://www.kaggle.com/datasets/gauravmalik26/food-delivery-dataset?select=train.csv
- Do Exploratory Data Analysis, create models using different algorithms and compare them using accuracy scores

**Comment by AadeshKabra** [comment]
Hi Can I work on this?

**Comment by AshishKingdom** [comment]
@AadeshKabra sure!! I have assigned you this
