### ISSUE TITLE
Airline Passenger Satisfaction

### ISSUE THREAD

**Issue by AshishKingdom** [DSC-JSS-NOIDA/ML-Hub#33]
- **Objective** : To create a model which can predict passenger's satisfaction level(Satisfaction, neutral or dissatisfaction)
- **Dataset Link** : https://www.kaggle.com/datasets/teejmahal20/airline-passenger-satisfaction
- Do Exploratory Data Analysis, create models using different algorithms and compare them using evaluation metrics.

**Comment by disuja7** [comment]
Hey @srivasPankhuri , Can you assign this project to me. I want to work on it.

**Comment by akash9579** [comment]
Hi @AshishKingdom @srivasPankhuri 
Can u assign me this issue
I am happy to contribute on this.

**Comment by srivasPankhuri** [comment]
Alright @akash9579 assigning it to you

**Comment by akash9579** [comment]
hey @srivasPankhuri  will you please merge my PR #42

**Comment by akash9579** [comment]
hey @srivasPankhuri  
I made changes as you suggest previously
will you review and merge my PR #52

**Comment by akash9579** [comment]
hey @AshishKingdom ,@srivasPankhuri 
I made changes as you suggest previously
will you review and merge my PR #52

**Comment by AshishKingdom** [comment]
Closing this issue as it is completed in PR #60
