### ISSUE TITLE
Water Quality Prediction

### ISSUE THREAD

**Issue by AshishKingdom** [DSC-JSS-NOIDA/ML-Hub#34]
- **Objective** : To create a model which can predict if the water is potable or not
- **Dataset Link** : https://www.kaggle.com/datasets/adityakadiwal/water-potability
- Do Exploratory Data Analysis, create models using different algorithms and compare them using evaluation metrics.

**Comment by aka-vm** [comment]
Hey. I would Like to work on this issue.
Can you assign it to me?

**Comment by AshishKingdom** [comment]
@aka-vm go ahead!
