### ISSUE TITLE
Estimate the weight of Fishes

### ISSUE THREAD

**Issue by AshishKingdom** [DSC-JSS-NOIDA/ML-Hub#4]
- **Objective** :  Create a model which can estimate the weight of fishes
- **Dataset Link** :  https://www.kaggle.com/datasets/aungpyaeap/fish-market?select=Fish.csv
- Do Exploratory Data Analysis, create models using different algorithms and compare them using accuracy scores.

**Comment by navya-Singla-1-3-0-9** [comment]
Please assign this issue to me.

**Comment by srivasPankhuri** [comment]
@navya-Singla-1-3-0-9 go ahead

**Comment by AadeshKabra** [comment]
Can I work on this?

**Comment by srivasPankhuri** [comment]
@AadeshKabra sure
