### ISSUE TITLE
Heart Stroke Prediction Web App

### ISSUE THREAD

**Issue by ankitkumar174** [DSC-JSS-NOIDA/ML-Hub#43]
- **Objective :** To predict the probability of Heart Strokes in humans.
- **Dataset :** https://www.kaggle.com/code/sakshamkaushal/heart-stroke-prediction-and-analysis/data
- Do Data Preprocessing, Data Minning, Data Analysis, create model using RandomForest Classifier, compare them using evaluation metrices and Deploy the model using Flask.

**Comment by AadeshKabra** [comment]
Hi, Can I work on this?

**Comment by ankitkumar174** [comment]
> Hi, Can I work on this?
> 

Sure

**Comment by AadeshKabra** [comment]
Could you assign me?

**Comment by ankitkumar174** [comment]
> Could you assign me?
> 

Connect me via https://beacons.ai/ankitkum

**Comment by srivasPankhuri** [comment]
@ankitkumar174 your PR has been merged
