### ISSUE TITLE
Cyberbullying Classification

### ISSUE THREAD

**Issue by AshishKingdom** [DSC-JSS-NOIDA/ML-Hub#66]
- **Objective** : To create a model which can predict whether a tweet is related to cyberbullying or not.
- **Dataset Link** : https://www.kaggle.com/datasets/andrewmvd/cyberbullying-classification
- Do Exploratory Data Analysis, create models using different algorithms and compare them using evaluation metrics.

**Comment by disuja7** [comment]
I want to work on it. Please assign this to me.

**Comment by srivasPankhuri** [comment]
@disuja7 assigning it to you

**Comment by disuja7** [comment]
@srivasPankhuri Project added, kindly check the file and merge the pull request.

**Comment by disuja7** [comment]
Hello @srivasPankhuri  are you there ? This is my 4th pull request for hactoberfest, Please merge it as early as possible.

**Comment by AshishKingdom** [comment]
@disuja7 Your PR has been merged.
