### ISSUE TITLE
Electrical Fault Detection

### ISSUE THREAD

**Issue by AshishKingdom** [DSC-JSS-NOIDA/ML-Hub#67]
- **Objective** : To create a model which can classify/detect fault in electrical power system.
- **Dataset Link** : https://www.kaggle.com/datasets/esathyaprakash/electrical-fault-detection-and-classification
- Do Exploratory Data Analysis, create models using different algorithms and compare them using evaluation metrics.

**Comment by aarushichopkar** [comment]
Hey, Can you assign me this task?

**Comment by AshishKingdom** [comment]
@aarushichopkar assigned! Go ahead!
