### ISSUE TITLE
BigMart Sales Analysis and Prediction

### ISSUE THREAD

**Issue by srivasPankhuri** [DSC-JSS-NOIDA/ML-Hub#7]
• **Objective** : Create a model to predict sales of BigMart.
• **Dataset** : https://www.kaggle.com/datasets/brijbhushannanda1979/bigmart-sales-data?select=Train.csv
• Do Exploratory Data Analysis, create models using different algorithms and compare them using accuracy scores

**Comment by Aakarsh00** [comment]
hey, can you assign me this model

**Comment by divik2510** [comment]
Hi @Aakarsh00 
You're already assigned to a project, complete that first then I'll assign this to you!

**Comment by pavitra-lalwani** [comment]
Hey @divik2510 ,I wish to work on this issue.
Can you please assign it to me?

**Comment by divik2510** [comment]
@pavitra-lalwani go ahead!
