### ISSUE TITLE
Loan Prediction

### ISSUE THREAD

**Issue by AshishKingdom** [DSC-JSS-NOIDA/ML-Hub#9]
- **Objective** : Create a model which can predict if the loan can be granted or not
- **Dataset Link** : https://www.kaggle.com/datasets/altruistdelhite04/loan-prediction-problem-dataset
- Do Exploratory Data Analysis, create models using different algorithms and compare them using evaluation metrics.

**Comment by Aakarsh00** [comment]
HEY, can you assign me this issue?

**Comment by srivasPankhuri** [comment]
@Aakarsh00 go ahead !

**Comment by disuja7** [comment]
Hello @srivasPankhuri , Can you assign this task to me. I have completed it.
